// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using campusakarya.Models;

#nullable disable

namespace campusakarya.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("campusakarya.Models.Community", b =>
                {
                    b.Property<int>("CommunityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommunityName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("CommunityID");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("campusakarya.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("EventID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("campusakarya.Models.Event_Community", b =>
                {
                    b.Property<int>("EventID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommunityID")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventID", "CommunityID");

                    b.HasIndex("CommunityID");

                    b.ToTable("Events_Communities");
                });

            modelBuilder.Entity("campusakarya.Models.Event_Community", b =>
                {
                    b.HasOne("campusakarya.Models.Community", "Community")
                        .WithMany("Events_Communities")
                        .HasForeignKey("CommunityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("campusakarya.Models.Event", "Event")
                        .WithMany("Events_Communities")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("campusakarya.Models.Community", b =>
                {
                    b.Navigation("Events_Communities");
                });

            modelBuilder.Entity("campusakarya.Models.Event", b =>
                {
                    b.Navigation("Events_Communities");
                });
#pragma warning restore 612, 618
        }
    }
}
